service:
  name: ${env:NAME}

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  timeout: 90
  runtime: nodejs14.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  versionFunctions: false
  logRetentionInDays: 30
package:
  individually: true
custom:
  urlPrefix: 'sls'
  esbuild:
    bundle: true
    minify: true
    packager: yarn
    plugins: esbuild-plugins.js
functions: ${file(./resources/lambda/functions.yml)}
resources:
  - ${file(./resources/config/iam.yml)}
